#!/bin/bash

#cdir=`pwd`
#java -cp $cdir/classes org.mycoz.Mycoz
cdir=`pwd`
JAVA_HOME=/usr/java/j2sdk
#srcdir=$cdir/src
classdir=$cdir/classes
libdir=$cdir/lib

export CLASSPATH=.:$classdir

libfilelist=`find $libdir -name "*.jar" -print`
for lf in $libfilelist
do
  export CLASSPATH=$CLASSPATH:$lf
done
#echo $CLASSPATH
echo "CLASSPATH:"
echo "$JAVA_HOME/bin/java -cp $CLASSPATH org.mycoz.Mycoz"
$JAVA_HOME/bin/java -cp $CLASSPATH org.mycoz.Mycoz


